// Generated by CoffeeScript 1.7.0
(function() {
  var DropPlugin, ever;

  ever = require('ever');

  require('string.prototype.endswith');

  module.exports = function(game, opts) {
    return new DropPlugin(game, opts);
  };

  DropPlugin = (function() {
    function DropPlugin(game, opts) {
      this.game = game;
      if (!this.game.isClient) {
        return;
      }
      if (this.game.materials.artPacks == null) {
        throw new Error('voxel-drop requires voxel-texture-shader with artPacks');
      }
      this.packs = this.game.materials.artPacks;
      this.body = ever(document.body);
      this.enable();
    }

    DropPlugin.prototype.enable = function() {
      this.body.on('dragover', this.dragover = function(ev) {
        ev.stopPropagation();
        return ev.preventDefault();
      });
      return this.body.on('drop', this.drop = (function(_this) {
        return function(mouseEvent) {
          var file, files, shouldAppend, _i, _len, _results;
          mouseEvent.stopPropagation();
          mouseEvent.preventDefault();
          console.log('drop', mouseEvent);
          files = mouseEvent.target.files || mouseEvent.dataTransfer.files;
          console.log('Dropped', files);
          _results = [];
          for (_i = 0, _len = files.length; _i < _len; _i++) {
            file = files[_i];
            console.log('Reading dropped', file);
            if (file.name.endsWith('.zip')) {
              shouldAppend = mouseEvent.shiftKey;
              _results.push(_this.loadArtPack(file, shouldAppend));
            } else if (file.name.endsWith('.js')) {
              _results.push(_this.loadScript(file));
            } else {
              _results.push(window.alert("Unrecognized file dropped: " + file.name + ". Try dropping a resourcepack/artpack (.zip)"));
            }
          }
          return _results;
        };
      })(this));
    };

    DropPlugin.prototype.readAll = function(file, cb) {
      var reader;
      reader = new FileReader();
      ever(reader).on('load', (function(_this) {
        return function(readEvent) {
          var result;
          if (readEvent.total !== readEvent.loaded) {
            return;
          }
          result = readEvent.currentTarget.result;
          return cb(result);
        };
      })(this));
      return reader;
    };

    DropPlugin.prototype.readAllText = function(file, cb) {
      return (this.readAll(file, cb)).readAsText(file);
    };

    DropPlugin.prototype.readAllData = function(file, cb) {
      return (this.readAll(file, cb)).readAsArrayBuffer(file);
    };

    DropPlugin.prototype.loadScript = function(file) {
      return this.readAllText(file, (function(_this) {
        return function(text) {
          var createCreatePlugin, createPlugin, e, name, opts, plugin;
          try {
            createCreatePlugin = new Function("var module = {exports: {}}; var require = " + _this.game.plugins.require + "; " + text + " return module.exports;");
          } catch (_error) {
            e = _error;
            window.alert("Exception loading plugin " + file.name + ": " + e);
            throw e;
          }
          createPlugin = createCreatePlugin();
          name = file.name;
          opts = {};
          console.log("loadScript #file.name = " + createPlugin);
          if (!createPlugin || typeof createPlugin !== 'function') {
            console.log("Ignored non-plugin " + name + ", returned " + createPlugin);
            return;
          }
          plugin = _this.game.plugins.instantiate(createPlugin, name, opts);
          if (!plugin) {
            return window.alert('Failed to load plugin ' + name);
          } else {
            return console.log("Loaded plugin: " + name + " = " + plugin);
          }
        };
      })(this));
    };

    DropPlugin.prototype.loadArtPack = function(file, shouldAppend) {
      return this.readAllData(file, (function(_this) {
        return function(arrayBuffer) {
          if (!shouldAppend) {
            _this.packs.clear();
          }
          _this.packs.addPack(arrayBuffer, file.name);
          return _this.game.showAllChunks();
        };
      })(this));
    };

    DropPlugin.prototype.disable = function() {
      this.body.removeListener('dragover', this.dragover);
      return this.body.removeListener('drop', this.drop);
    };

    return DropPlugin;

  })();

}).call(this);
