// Generated by CoffeeScript 1.6.3
(function() {
  var DropPlugin, ever;

  ever = require('ever');

  module.exports = function(game, opts) {
    return new DropPlugin(game, opts);
  };

  DropPlugin = (function() {
    function DropPlugin(game, opts) {
      this.game = game;
      this.body = ever(document.body);
      this.enable();
    }

    DropPlugin.prototype.enable = function() {
      this.body.on('dragover', this.dragover = function(ev) {
        ev.stopPropagation();
        return ev.preventDefault();
      });
      return this.body.on('drop', this.drop = function(ev) {
        ev.stopPropagation();
        ev.preventDefault();
        return console.log('drop', ev);
      });
    };

    DropPlugin.prototype.disable = function() {
      this.body.removeListener('dragover', this.dragover);
      return this.body.removeListener('drop', this.drop);
    };

    return DropPlugin;

  })();

}).call(this);
